# GLOBAL SITE SETTINGS

cname: icresolution.yourwebvisual.com

# META
title: Integrated Conflict Resolution
title_homepage: Integrated Conflict Resolution
company: Integrated Conflict Resolution
description: ...

# DEVELOPER
allow_robots: false
github_repo_owner: liquidvisual
github_repo_path: https://github.com/liquidvisual/berrill-0717
github_repo_name:
jekyll_version: 3.5.0

# OFFICES
offices:
  - title:
    address: Address goes here (or PO Box?)
    phone: 1300 437 376
    email: info@icresolution.com.au

# SOCIAL MEDIA
facebook:
linked_in:
google_plus:
instagram:

# GOOGLE
google_analytics: "UA-XXXXXXXX-X"

# AUTHOR
author:
  title: Much Media
  url: http://muchmedia.com.au
  logo: /assets/img/ui/logo-much-media.svg
  description: WEBSITE BY MUCH MEDIA